spring:
  redis:
    database: 0
    host: 45.32.41.152
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        min-idle: 0
        max-idle: 10
        max-wait: -1
    timeout: 1000